
Sandstorm:
  GedmoTranslatableConnector:
    locale: mul_ZZ
    defaultLocale: mul_ZZ
    translationFallback: false
    persistDefaultLocaleTranslation: false
Neos:
  Flow:
    object:
      includeClasses:
        gedmo.doctrineextensions:
          - 'Gedmo\\Translatable\\Entity'
    persistence:
      doctrine:
        eventListeners:
          Gedmo\Translatable\TranslatableListener:
            events:
              - postLoad
              - postPersist
              - preFlush
              - onFlush
              - loadClassMetadata
            listener: Gedmo\Translatable\TranslatableListener
